apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  namespace: __deploymentEnvironment__
  name: hello-__deploymentEnvironment__
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: hello-__deploymentEnvironment__
