apiVersion: v1
kind: Service
metadata:
  namespace: __deploymentEnvironment__
  name: hello-__deploymentEnvironment__
  labels:
    app: hello-__deploymentEnvironment__
spec:
  ports:
    - port: 80
      protocol: TCP
  type: NodePort
  selector:
    app: hello-__deploymentEnvironment__
