apiVersion: elbv2.k8s.aws/v1beta1
kind: TargetGroupBinding
metadata:
  namespace: __deploymentEnvironment__
  name: hello-__deploymentEnvironment__-tgb
spec:
  serviceRef:
    name: hello-__deploymentEnvironment__
    port: 80
  targetGroupARN: "__TARGET_GROUP_ARN__"
  targetType: ip
